import type { Metadata } from "next";
import "./globals.css";

import { Archivo } from "next/font/google";

const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "700", "800", "900"],
  variable: "--font-archivo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className=" bg-emerald-900 overflow-x-hidden">
      <body className={`${archivo.variable}`}>{children}</body>
    </html>
  );
}
